### ISSUE TITLE
navigate to home showing cannot get /home

### ISSUE THREAD

**Issue by rahulnarula297** [Bpitorg/BPIT_Frontend#11]
in the sign in page , link to navigate back to home showing error
![2020-06-17 (3)](https://user-images.githubusercontent.com/60522765/84882580-19637280-b0ad-11ea-93f6-f6460954fcd1.png)
![2020-06-17 (1)_LI](https://user-images.githubusercontent.com/60522765/84882624-27b18e80-b0ad-11ea-9ae8-d325cd6a0fbc.jpg)

**Comment by ChauhanRitika** [comment]
issue resolved
