### ISSUE TITLE
Increase image height on home page 

### ISSUE THREAD

**Issue by rishabhgupta03** [Bpitorg/BPIT_Frontend#12]
the images on the front page appears too narrow and their height needs to be increased for better page viewing .

![image](https://user-images.githubusercontent.com/44132253/84888850-8c70e700-b0b5-11ea-900c-147854a6d744.png)

**Comment by AchalKaushik** [comment]
i guess that needs to be reviewed as if image size increases We will not be able to find news/notice/event section visible upfront

**Comment by rishabhgupta03** [comment]
increasing a bit won't make much difference to news/notice/event section as they are already partially visible or we can reduce width then, displaying at least 2 images together

**Comment by AchalKaushik** [comment]
i was of the opinion that viewer should get the idea first off where the information can be found in terms of news/notice etc. so see how better it can be done

**Comment by Mayankjh** [comment]
@rishabhgupta03  this design has already been discussed with the HoD's of the respective department and the view was changed in accordance with their suggestions. Earlier the images were on a full-screen slider. We'll see in further meetings if we need to change this.
