### ISSUE TITLE
update data on 

### ISSUE THREAD

**Issue by AchalKaushik** [Bpitorg/BPIT_Frontend#19]
Need to update NIRF ranking with logo (may choose better logo) 

![nirf](https://user-images.githubusercontent.com/21976104/85785022-82e71f00-b746-11ea-87ee-90aee4d709f9.png)

Bhagwan Parshuram Institute of Technology (Under graduate Engineering College,  established by Bhartiya Brahamin Charitable Trust) is ranked among first 300 Engineering institutes in country by the National Institute Ranking Framework (MHRD).

[https://bpit.herokuapp.com/#/aboutus/certifications](url)

**Comment by jindal2209** [comment]
Will be updated ...
Informed to ritika
