### ISSUE TITLE
Enhance UI

### ISSUE THREAD

**Issue by Mayankjh** [Bpitorg/BPIT_Frontend#2]

**Comment by rahulnarula297** [comment]
adding mailto reference and website link in the contact section 

<p>Email:<a href="mailto:bpitindia@yahoo.com"> bpitindia@yahoo.com</a></p>
<p>Website:<a href=" http://www.bpitindia.com"> bpitindia.com</a></p>

**Comment by Mayankjh** [comment]
@ChauhanRitika add the changes

**Comment by ChauhanRitika** [comment]
changes added
