### ISSUE TITLE
Library page

### ISSUE THREAD

**Issue by AchalKaushik** [Bpitorg/BPIT_Frontend#20]
May be the names font and colour changed to distinguish on the page   i.e. **_Norman Cousins_** &  **_H.W. Beecher_**

https://bpit.herokuapp.com/#/facilities/library

A library is the delivery room for the birth of ideas, a place where history comes to life. **_Norman Cousins_**
A library is not a luxury but one of the necessities of life. **_H.W. Beecher_**

**Comment by ChauhanRitika** [comment]
changes added
