### ISSUE TITLE
placement page

### ISSUE THREAD

**Issue by AchalKaushik** [Bpitorg/BPIT_Frontend#21]
Following text needs to be updated on the page [https://bpit.herokuapp.com/#/placements/training](url)

The Training & Placement Cell at BPIT is one of the strongest pillar of the institute. The T&P team constitutes dedicated professionals working continuously under the leadership of Prof. Abhishek Swaroop & Mr. Sanjay Dureja.

**Comment by ChauhanRitika** [comment]
changes added
