### ISSUE TITLE
NIRF data to be updated 

### ISSUE THREAD

**Issue by AchalKaushik** [Bpitorg/BPIT_Frontend#23]
Following PDF files from [http://www.bpitindia.com/nirf.html](url) can be copied [https://bpit.herokuapp.com/#/nirf](url)
Overall NIRF Data for 2020 | PDF | 09/01/20
Overall NIRF Data for 2019 | PDF | 08/01/19
MBA NIRF Data for 2019 | PDF | 08/01/19
B.Tech. NIRF Data for 2019 | PDF | 08/01/19

**Comment by ChauhanRitika** [comment]
data added
