### ISSUE TITLE
placing sign in next to contact us

### ISSUE THREAD

**Issue by rishabhgupta03** [Bpitorg/BPIT_Frontend#25]

**Comment by rishabhgupta03** [comment]
the sign in button is too small to find at first look and it can be placed next to contact us tab for better viewing

**Comment by ChauhanRitika** [comment]
The position of the sign-in button cannot be changed, as if we change it, then the position of Hi will also get change, which doesn't look good next to contact.
So it would be better if we leave it as it is.
