### ISSUE TITLE
BPIT logo and banner not properly aligned

### ISSUE THREAD

**Issue by AchalKaushik** [Bpitorg/BPIT_Frontend#4]
Home page [https://bpit.herokuapp.com/#/home](url)
The BPIT logo and banner are not properly aligned
BPIT logo  should be shifted towards its left side
Banner text should be at the center
Right side LOGO is also missing

**Comment by AchalKaushik** [comment]
> Right side logo is added
> BPIT logo and banner are now properly aligned.

It seems not done yet!

![logo](https://user-images.githubusercontent.com/21976104/85788115-12da9800-b74a-11ea-98fa-6c2ce0619604.png)

**Comment by AchalKaushik** [comment]
It seems not done yet!

![logo](https://user-images.githubusercontent.com/21976104/85788115-12da9800-b74a-11ea-98fa-6c2ce0619604.png)

**Comment by ChauhanRitika** [comment]
changes added
