### ISSUE TITLE
mobile view incorrect

### ISSUE THREAD

**Issue by AchalKaushik** [Bpitorg/BPIT_Frontend#5]
Following pages giving distorted view on mobile view
Text: From the desk of the Chairman
[https://bpit.herokuapp.com/#/aboutus/chairmansmessage](url)
Text: From the desk of the principal
[https://bpit.herokuapp.com/#/aboutus/principalsmessage](url)

**Comment by ChauhanRitika** [comment]
mobile view is now correct
