### ISSUE TITLE
check box and "placement login"not properly aligned

### ISSUE THREAD

**Issue by rishabhgupta03** [Bpitorg/BPIT_Frontend#7]
the check box and "placement login" are not properly  aligned under member login sign in tab.
needs to add a space betwwen two  

![image](https://user-images.githubusercontent.com/44132253/84875205-46ab2300-b0a3-11ea-8733-fb6e507c6123.png)

**Comment by Mayankjh** [comment]
@rishabhgupta03  can you work on angular?

**Comment by rishabhgupta03** [comment]
nope, i can't

**Comment by Mayankjh** [comment]
no issues...

**Comment by ChauhanRitika** [comment]
checkbox and "placement login" is now properly aligned
